# Generated by Django 6.0.2 on 2026-02-13 01:07

import django.core.validators
import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('FISICO', 'Físicos'), ('QUIMICO', 'Químicos'), ('MICROBIOLOGICO', 'Microbiológicos')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Análisis',
                'verbose_name_plural': 'Tipos de Análisis',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('solicitante_nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('solicitante_area', models.CharField(choices=[('AGRONOMIA', 'Agronomía'), ('PRODUCCION', 'Producción'), ('ASEGURAMIENTO_CALIDAD', 'Aseguramiento de Calidad'), ('COMERCIAL', 'Comercial')], max_length=30, verbose_name='Área/Departamento')),
                ('solicitante_cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('solicitante_email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('estado', django_fsm.FSMField(choices=[('RADICADA', 'Radicada'), ('PENDIENTE_RECEPCION', 'Pendiente de Recepción'), ('RECIBIDA', 'Recibida'), ('EN_ANALISIS', 'En Análisis'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='RADICADA', max_length=50, protected=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Análisis',
                'verbose_name_plural': 'Solicitudes de Análisis',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('can_receive_samples', 'Puede recibir muestras'), ('can_analyze_samples', 'Puede analizar muestras'), ('can_complete_orders', 'Puede completar órdenes')],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de recepción')),
                ('condicion', models.CharField(choices=[('CONFORME', 'Conforme'), ('NO_CONFORME', 'No Conforme')], max_length=15, verbose_name='Condición de llegada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Recepción de Muestra',
                'verbose_name_plural': 'Recepciones de Muestras',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('campo_modificado', models.CharField(max_length=100)),
                ('valor_anterior', models.TextField()),
                ('valor_nuevo', models.TextField()),
                ('descripcion', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Historial de Cambios',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('numero_lote', models.CharField(max_length=100, verbose_name='Número de lote')),
                ('fecha_fabricacion', models.DateField(verbose_name='Fecha de fabricación')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento/retest')),
                ('numero_muestras_enviadas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de muestras enviadas')),
                ('cantidad_por_muestra', models.CharField(max_length=100, verbose_name='Cantidad por muestra')),
                ('tipo_muestra', models.CharField(choices=[('FLOR', 'Flor'), ('EXTRACTO_CRUDO', 'Extracto crudo'), ('AISLADO', 'Aislado'), ('DESTILADO', 'Destilado')], max_length=20, verbose_name='Tipo de muestra')),
                ('condiciones_almacenamiento', models.CharField(choices=[('AMBIENTE', 'Ambiente'), ('REFRIGERACION', 'Refrigeración'), ('CONGELACION', 'Congelación')], max_length=20, verbose_name='Condiciones de almacenamiento')),
                ('fecha_entrega_laboratorio', models.DateField(verbose_name='Fecha de entrega al laboratorio')),
                ('tipo_analisis', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('ESTABILIDAD', 'Estabilidad'), ('INVESTIGACION', 'Investigación'), ('LIBERACION_LOTE', 'Liberación de lote')], max_length=20, verbose_name='Tipo de análisis')),
                ('protocolo_analitico', models.CharField(blank=True, max_length=200, verbose_name='Protocolo analítico')),
                ('requiere_coa', models.BooleanField(default=False, verbose_name='Requiere CoA')),
                ('especificaciones', models.TextField(blank=True, verbose_name='Especificaciones')),
                ('prioridad', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=10, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('debe_devolverse', models.BooleanField(default=False, verbose_name='¿Debe devolverse?')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muestras', to='solicitudes.solicitud')),
                ('analisis_solicitados', models.ManyToManyField(to='solicitudes.tipoanalisis', verbose_name='Análisis solicitados')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
                'ordering': ['id'],
            },
        ),
    ]
