# Generated by Django 6.0.2 on 2026-02-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante_cargo',
            field=models.CharField(choices=[('CONTROL_CALIDAD', 'Control de Calidad'), ('INGENIERO_AGRONOMO', 'Ingeniero Agrónomo'), ('ANALISTA_LABORATORIO', 'Analista de Laboratorio'), ('SUPERVISOR_PRODUCCION', 'Supervisor de Producción'), ('COORDINADOR', 'Coordinador'), ('GERENTE', 'Gerente'), ('OTRO', 'Otro')], max_length=50, verbose_name='Cargo'),
        ),
    ]
