# Generated by Django 6.0.2 on 2026-02-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_solicitud_solicitante_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante_area',
            field=models.CharField(choices=[('AGRONOMIA', 'Agronomía'), ('PRODUCCION', 'Producción'), ('ASEGURAMIENTO_CALIDAD', 'Aseguramiento de Calidad'), ('CONTROL_CALIDAD', 'Control de Calidad'), ('COMERCIAL', 'Comercial')], max_length=30, verbose_name='Área/Departamento'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante_cargo',
            field=models.CharField(choices=[('INGENIERO_AGRONOMO', 'Ingeniero Agrónomo'), ('ANALISTA_LABORATORIO', 'Analista de Laboratorio'), ('SUPERVISOR_PRODUCCION', 'Supervisor de Producción'), ('COORDINADOR', 'Coordinador'), ('GERENTE', 'Gerente'), ('JEFE_DEPARTAMENTO', 'Jefe de Departamento'), ('OTRO', 'Otro')], max_length=50, verbose_name='Cargo'),
        ),
    ]
