# Generated by Django 6.0.2 on 2026-02-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_alter_solicitud_solicitante_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='solicitante_cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
    ]
